In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/dmmml project/healthcare-dataset-stroke-data.csv')

In [ ]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
df.shape

(5110, 12)

In [ ]:
# Dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [ ]:
# Check missing value
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [ ]:
# Drop row with missing value
df = df.dropna(axis=0)
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
5     56669    Male  81.0             0              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5104  14180  Female  13.0             0              0           No   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
5           Private          Urban             186.21  29.0  formerly smoked   
...             ...            ...                ...   ...              ...   
5104       children          Rural             103.08  18.6          Unknown   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
2          1  
3          1  
4          1  
5          1  
...      ...  
5104       0  
5106       0  
5107       0  
5108       0  
5109       0  

[4909 rows x 12 columns]

In [ ]:
# Drop id 
df = df.drop(['id'], axis=1)
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
2       Male  80.0             0              1          Yes        Private   
3     Female  49.0             0              0          Yes        Private   
4     Female  79.0             1              0          Yes  Self-employed   
5       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
5104  Female  13.0             0              0           No       children   
5106  Female  81.0             0              0          Yes  Self-employed   
5107  Female  35.0             0              0          Yes  Self-employed   
5108    Male  51.0             0              0          Yes        Private   
5109  Female  44.0             0              0          Yes       Govt_job   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
2             Rural             105.92  32.5     never smoked       1  
3             Urban             171.23  34.4           smokes       1  
4             Rural             174.12  24.0     never smoked       1  
5             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
5104          Rural             103.08  18.6          Unknown       0  
5106          Urban             125.20  40.0     never smoked       0  
5107          Rural              82.99  30.6     never smoked       0  
5108          Rural             166.29  25.6  formerly smoked       0  
5109          Urban              85.28  26.2          Unknown       0  

[4909 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
from pandas.core.dtypes.common import is_numeric_dtype

# Label Encoding
le = LabelEncoder() # method initialization

for col in df.columns :
   if is_numeric_dtype(df[col]):
       continue

   df[col]=le.fit_transform(df[col])

df.head()

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       1  67.0             0              1             1          2   
2       1  80.0             0              1             1          2   
3       0  49.0             0              0             1          2   
4       0  79.0             1              0             1          3   
5       1  81.0             0              0             1          2   

   Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0               1             228.69  36.6               1       1  
2               0             105.92  32.5               2       1  
3               1             171.23  34.4               3       1  
4               0             174.12  24.0               2       1  
5               1             186.21  29.0               1       1

In [ ]:
# Define X (Feature) and Y (Target)


X = df.drop('stroke',axis=1)

y = df['stroke']

In [ ]:
# Split dataset to traning and testing set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# Modelling
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC


classifier_KNN = KNeighborsClassifier()
classifier_DT = DecisionTreeClassifier()
classifier_GNB = GaussianNB()
classifier_log=LogisticRegression()

### **1.KNN**

In [ ]:
classifier_KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
KNN = classifier_KNN.predict(X_test)
dataEvaluation=pd.DataFrame({"y_Predict":KNN, "y_Actual":y_test})
dataEvaluation

y_Predict  y_Actual
4867          0         0
608           0         0
1453          0         0
4560          0         0
4362          0         0
...         ...       ...
735           0         0
4832          0         0
4088          0         0
261           0         0
3106          0         0

[1228 rows x 2 columns]

In [ ]:
classifier_KNN.score(X_test,y_test)

0.9527687296416938

In [ ]:
y_prediction = classifier_KNN.predict(X_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_prediction)
cm

array([[1170,    9],
       [  49,    0]])

# **2. Decision Tree**



In [ ]:
classifier_DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
classi = classifier_DT.predict(X_test)
dataEvaluation=pd.DataFrame({"y_Predict":classi, "y_Actual":y_test})
dataEvaluation

y_Predict  y_Actual
4867          0         0
608           0         0
1453          0         0
4560          0         0
4362          0         0
...         ...       ...
735           0         0
4832          0         0
4088          0         0
261           0         0
3106          0         0

[1228 rows x 2 columns]

In [ ]:
classifier_DT.score(X_test,y_test)

0.9201954397394136

In [ ]:
y_prediction = classifier_DT.predict(X_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_prediction)
cm

array([[1121,   58],
       [  40,    9]])

# **3. GaussianNB**

In [ ]:
classifier_GNB.fit(X_train, y_train)

GaussianNB()

In [ ]:
GNB = classifier_GNB.predict(X_test)
dataEvaluation=pd.DataFrame({"y_Predict":GNB, "y_Actual":y_test})
dataEvaluation

y_Predict  y_Actual
4867          0         0
608           0         0
1453          1         0
4560          1         0
4362          1         0
...         ...       ...
735           0         0
4832          0         0
4088          1         0
261           0         0
3106          0         0

[1228 rows x 2 columns]

In [ ]:
classifier_GNB.score(X_test,y_test)

0.8705211726384365

In [ ]:
y_prediction = classifier_GNB.predict(X_test)
y_prediction

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_prediction)
cm

array([[1044,  135],
       [  24,   25]])

# **4.LogisticRegression**

In [ ]:
classifier_log.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
log= classifier_log.predict(X_test)
dataEvaluation=pd.DataFrame({"y_Predict":log, "y_Actual":y_test})
dataEvaluation

y_Predict  y_Actual
4867          0         0
608           0         0
1453          0         0
4560          0         0
4362          0         0
...         ...       ...
735           0         0
4832          0         0
4088          0         0
261           0         0
3106          0         0

[1228 rows x 2 columns]

In [ ]:
classifier_log.score(X_test,y_test)

0.9600977198697068

In [ ]:
y_prediction = classifier_log.predict(X_test)
y_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_prediction)
cm

array([[1179,    0],
       [  49,    0]])